modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="coordinates"
version="1.0.1"
displayName="coordinates"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/unixgeek/minecraft-coordinates-mod"
authors="Gunter Wambaugh"
description='''
Show coordinates on screen.
'''

[[dependencies.coordinates]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




